from config.private_cfg import *

is_debug = True

if is_debug:
    BOT_TOKEN = BOT_TOKEN_TEST
    DB_PASSWORD = DB_PASSWORD_TEST
    PAYMENT_TOKEN = PAYMENT_TOKEN_TEST
    TRELLO_KEY = TRELLO_KEY_TEST
    TRELLO_TOKEN = TRELLO_TOKEN_TEST
    TRELLO_SECRET = TRELLO_SECRET_TEST
else:
    BOT_TOKEN = BOT_TOKEN_PROD
    DB_PASSWORD = DB_PASSWORD_PROD
    PAYMENT_TOKEN = PAYMENT_TOKEN_PROD
    TRELLO_KEY = TRELLO_KEY_PROD
    TRELLO_TOKEN = TRELLO_TOKEN_PROD
    TRELLO_SECRET = TRELLO_SECRET_PROD

